sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: npm install
script: npm run validate
after_script: npx codecov
branches:
  only: master
